#!/bin/sh
sh ~/.config/river/keymaps.sh &
#decorations and cursor follow
rivertile -view-padding 0 -outer-padding 0 &
riverctl background-color 0x1e1e2e
riverctl border-color-focused 0xcdd6f4
riverctl border-color-unfocused 0x1e1e2e
riverctl border-width 3 
riverctl focus-follows-cursor normal
riverctl rule-add -app-id "*" ssd
riverctl set-cursor-warp on-focus-change
riverctl default-layout rivertile
riverctl set-repeat 50 300
riverctl xcursor-theme Bibata-Modern-Classic 24
export XCURSOR_THEME=Bibata-Modern-Classic
export XCURSOR_SIZE=24
export XDG_CURRENT_DESKTOP=river
export XDG_SESSION_DESKTOP=river
export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORMTHEME=qt6ct
export QT_STYLE_OVERRIDE=kvantum



#autostart stuff
dunst &
copyq &
easyeffects --gapplication-service &
sh ~/.local/bin/psc.sh &
sh ~/.local/bin/yambar.sh & 
xremap ~/.config/xremap/config.yml &
kitty -e rmpc &
sh ~/.local/share/screenshare.sh &
