palette = "catppuccin_mocha"
format = """$directory$git_branch$git_status$character
\r"""

[directory]
format = 	'[$path]($style)[$read_only]($read_only_style) '
truncation_symbol = "~/"
style = "bold red"

# Git branch: simple green with branch symbol
[git_branch]
format = "[$branch(:$remote_branch)]($style) "
style = "bold mauve"

# Git status: minimal icons in yellow
[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = "≠"
ahead = "↑"
behind = "↓"
staged = "●"
untracked = "…"
modified = "✚"
stashed = "⚑"
renamed = "➜"
deleted = "✖"
style = "bold peach"

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[time]
disabled = true 

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
